// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomBookingApp.api.Data;

#nullable disable

namespace RoomBookingApp.Api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260210184216_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("RoomBookingApp.api.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 11, 1, 42, 15, 440, DateTimeKind.Local).AddTicks(2557),
                            EndTime = new DateTime(2026, 2, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Purpose = "Rapat HIMIT",
                            RequesterName = "Adryan",
                            RoomName = "Ruang Teater",
                            StartTime = new DateTime(2026, 2, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
